### ISSUE TITLE
Initial design doc comments

### ISSUE THREAD

**Issue by mcclure** [Strikingwolf/Sophia#1]
Here are some thoughts on the current design.md:

"Storage":
- Maybe a line for "list of other packages required by this one"-- this might not be needed in version 0, but it's a pretty necessary idea.

"Dependency Installation"
- "If they are local dependencies they will install to .emilylocallibs in the project folder. If they are global dependencies then they will install to ~/.emilylibs"
  What is the difference? How does it tell the difference?
  I would like to request the "local sandbox" not be an invisible file. Maybe begin with an underscore because a package can't do that?

"Sophia dependency file"
I'm sorry, I do not quite understand this section. We can discuss on IRC.

"Sophia Commands"
- I think what would be consistent with other dependency tools is if "install" were the default to install. i don't think I would guess "get". Also most dependency tools assume you want recursive fetch (the equivalent of getAll). Maybe instead of "get" and "getAll" it could be "install" for "install plus deps" and "install --one" for "install by itself" (actually, honestly, i don't think installing by itself should be legal-- if it actually does depend on those other things, then installing it by itself is breaking your install!)
- Is "run" appropriate for sophia? I was just going to put the -m run version into emily itself.
- Do you need an "update" for fetching the contents of the big meta repo? Normal install tools seem to have install, update, and upgrade commands.

**Comment by FayeAlephNil** [comment]
I'll add in the storage thing

Difference is local is project specific. Tells the difference by install location. I'll change it to not be an invisible file

The sophia dependency file would basically list all the dependencies a project has. This could actually be used to omit the required depends on list in storage by doing a getAll (or fetch) on all the dependencies.
- I'll use install instead of get
- The getAll uses the Sophia dep file to get the dependencies. Kinda like bundler files do for Ruby gems (http://bundler.io/)
- Oh you were? I'll remove it
- I'll add those commands

**Comment by mcclure** [comment]
i think upgrade isn't useful until we have versions for things.

Re getAll: Oh! Okay. Here is a thought though: Why not just let the sophia dep file be a json file of essentially the same format as the "metadata json files" from the "main repository"? I think opam does this. Then you could think of the "get" and "getAll" as basically the same verb, and in some cases you're installing from a name and in some cases from a file.

**Comment by FayeAlephNil** [comment]
Just preparing for the future :laughing: 

That sounds good
